package com.recreo.enums;

public enum PermissionsEnum {
    USERS_READ,
    USERS_READ_WRITE,
    PROFILES_READ,
    PROFILES_READ_WRITE,
    MUNICIPALITIES_READ,
    MUNICIPALITIES_READ_WRITE,
    EVENTS_READ,
    EVENTS_READ_WRITE,
    POINTS_OF_INTEREST_READ,
    POINTS_OF_INTEREST_READ_WRITE,
    TRAVELS_READ,
    TRAVELS_READ_WRITE,
    CATEGORIES_READ,
    CATEGORIES_READ_WRITE
}
